// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ufRJwczoCxScz9fLJPcGNeX5SDP-6hI',
    appId: '1:743905793671:web:bb64c25340e0814bd84a22',
    messagingSenderId: '743905793671',
    projectId: 'educare-ae115',
    authDomain: 'educare-ae115.firebaseapp.com',
    storageBucket: 'educare-ae115.firebasestorage.app',
    measurementId: 'G-7CSNHWJ23F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQAGxIIeaxVuzAI9cPTV4XCrVDM1uyIeg',
    appId: '1:743905793671:android:b3170049424b305cd84a22',
    messagingSenderId: '743905793671',
    projectId: 'educare-ae115',
    storageBucket: 'educare-ae115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABWHCKJyrT9BkkAfIx-LVGozC8B6rHzcM',
    appId: '1:743905793671:ios:3479d4db21df27ced84a22',
    messagingSenderId: '743905793671',
    projectId: 'educare-ae115',
    storageBucket: 'educare-ae115.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABWHCKJyrT9BkkAfIx-LVGozC8B6rHzcM',
    appId: '1:743905793671:ios:3479d4db21df27ced84a22',
    messagingSenderId: '743905793671',
    projectId: 'educare-ae115',
    storageBucket: 'educare-ae115.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ufRJwczoCxScz9fLJPcGNeX5SDP-6hI',
    appId: '1:743905793671:web:ec3d0140199f011bd84a22',
    messagingSenderId: '743905793671',
    projectId: 'educare-ae115',
    authDomain: 'educare-ae115.firebaseapp.com',
    storageBucket: 'educare-ae115.firebasestorage.app',
    measurementId: 'G-1YVJ68EG3M',
  );
}
