name: Educare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  cupertino_icons: ^1.0.8
  email_validator: ^2.1.17
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^5.6.5
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/create_account.png
    - assets/images/welcome_to_educare.png
    - assets/images/google_logo.png
    - assets/images/logo.png
    - assets/images/chatbot_logo.png
    - assets/images/child_profile.png
    